name: Pipeline Test

on:
  workflow_dispatch:  # Manual trigger only
  schedule:
    - cron: '0 6 * * 1'  # Weekly on Monday

jobs:
  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create directories
      run: |
        mkdir -p data/raw data/processed data/analytics logs

    - name: Create .env file
      run: |
        cp .env.example .env || touch .env
        echo "AIRFLOW_UID=$(id -u)" >> .env

    - name: Start Docker Compose
      run: |
        docker-compose up -d
        echo "Services starting..."
        sleep 20

    - name: Check service status
      run: |
        docker-compose ps

    - name: Wait for PostgreSQL
      run: |
        for i in {1..30}; do
          docker-compose exec -T postgres pg_isready -U airflow && break
          echo "Waiting for PostgreSQL... ($i/30)"
          sleep 2
        done
        docker-compose exec -T postgres pg_isready -U airflow || exit 1

    - name: Check database
      run: |
        docker-compose exec -T postgres psql -U airflow -d jobs_db -c "SELECT version();" || echo "Database check failed"

    - name: Wait for Airflow
      run: |
        for i in {1..40}; do
          curl -sf http://localhost:8080/health && break
          echo "Waiting for Airflow... ($i/40)"
          sleep 3
        done

    - name: List DAGs
      run: |
        docker-compose exec -T airflow-webserver airflow dags list || echo "Could not list DAGs"
      continue-on-error: true

    - name: Check for DAG errors
      run: |
        docker-compose exec -T airflow-webserver airflow dags list-import-errors || echo "No import errors check available"
      continue-on-error: true

    - name: Show logs on failure
      if: failure()
      run: |
        echo "=== Airflow Webserver ==="
        docker-compose logs --tail=50 airflow-webserver
        echo "=== Airflow Scheduler ==="
        docker-compose logs --tail=50 airflow-scheduler
        echo "=== PostgreSQL ==="
        docker-compose logs --tail=30 postgres

    - name: Cleanup
      if: always()
      run: |
        docker-compose down -v
